language: python
python: 2.7
sudo: true
cache:
  directories:
    - eggs
    - downloads
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - pip install -r requirements.txt
  - buildout -N buildout:download-cache=downloads annotate
  - buildout -t 30 buildout:download-cache=downloads
script: bin/test
